import { defineField, defineType } from "sanity";

export const film = defineType({
  name: "film",
  title: "Film",
  type: "document",
  groups: [
    { name: "main", title: "Informations" },
    { name: "media", title: "Médias" },
    { name: "billetterie", title: "Billetterie" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Titre",
      type: "string",
      group: "main",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "main",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "originalTitle",
      title: "Titre original (si différent)",
      type: "string",
      group: "main",
    }),
    defineField({
      name: "director",
      title: "Réalisateur·rice",
      type: "string",
      group: "main",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "year",
      title: "Année",
      type: "number",
      group: "main",
    }),
    defineField({
      name: "country",
      title: "Pays",
      type: "string",
      group: "main",
      description: "Ex. Suisse, France, États-Unis",
    }),
    defineField({
      name: "duration",
      title: "Durée (minutes)",
      type: "number",
      group: "main",
    }),
    defineField({
      name: "language",
      title: "Langue",
      type: "string",
      group: "main",
      description: "Ex. VO",
    }),
    defineField({
      name: "subtitles",
      title: "Sous-titres",
      type: "string",
      group: "main",
      description: "Ex. st fr/all",
    }),
    defineField({
      name: "ageRating",
      title: "Âge conseillé",
      type: "string",
      group: "main",
      description: "Ex. 12 ans",
    }),
    defineField({
      name: "genres",
      title: "Genres / mots-clés",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      group: "main",
    }),
    defineField({
      name: "status",
      title: "Statut",
      type: "string",
      group: "main",
      options: {
        list: [
          { title: "À l'affiche", value: "a-laffiche" },
          { title: "Avant-première", value: "avant-premiere" },
          { title: "Prochainement", value: "prochainement" },
          { title: "Cycle / évènement", value: "cycle" },
          { title: "Passé", value: "passe" },
        ],
        layout: "radio",
      },
      initialValue: "a-laffiche",
    }),
    defineField({
      name: "synopsis",
      title: "Synopsis",
      type: "text",
      rows: 5,
      group: "main",
    }),
    defineField({
      name: "posterSize",
      title: "Poids visuel dans la grille",
      type: "string",
      group: "main",
      description:
        "Contrôle la taille de l'affiche dans la grille asymétrique de la page Films et de l'accueil.",
      options: {
        list: [
          { title: "Grand format", value: "large" },
          { title: "Format moyen", value: "medium" },
          { title: "Petit format", value: "small" },
        ],
      },
      initialValue: "medium",
    }),
    defineField({
      name: "featuredHome",
      title: "Mettre en avant sur l'accueil",
      type: "boolean",
      group: "main",
      initialValue: false,
    }),
    defineField({
      name: "poster",
      title: "Affiche",
      type: "image",
      group: "media",
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "stillImages",
      title: "Photos du film",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      group: "media",
    }),
    defineField({
      name: "trailerUrl",
      title: "Bande-annonce (URL YouTube / Vimeo)",
      type: "url",
      group: "media",
    }),
    defineField({
      name: "review",
      title: "Critique mise en avant",
      type: "reference",
      to: [{ type: "review" }],
      group: "main",
    }),
    defineField({
      name: "price",
      title: "Prix (CHF)",
      type: "string",
      group: "billetterie",
      description: "Ex. 16.- / 12.- (réduit). Utilisé si la séance n'a pas de prix propre.",
    }),
    defineField({
      name: "sumupCheckoutUrl",
      title: "Lien de paiement SumUp par défaut",
      type: "url",
      group: "billetterie",
      description:
        "Lien utilisé pour ce film si une séance précise n'a pas son propre lien SumUp.",
    }),
  ],
  orderings: [
    {
      title: "Titre A-Z",
      name: "titleAsc",
      by: [{ field: "title", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "director",
      media: "poster",
    },
  },
});
